name: gamecakejam
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: gamecake examples # 79 char long summary
description: |
  Contains open source examples for gamecake.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

architectures:
  - build-on: amd64
    run-on: all


parts:

  gamecakejam:

    plugin: make

    source: .

    override-build: |
      ./make

apps:

  gamecakejam:

    command: gamecakejam


plugs:
  gamecake:
    interface: content
    content: executables
    target: $SNAP/gamecake-bin
    default-provider: gamecake:gamecake
