name: gamecakejam
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: gamecake examples # 79 char long summary
description: |
  Contains open source examples for gamecake.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

architectures:
  - build-on: amd64
    run-on: all


parts:

  gamecakejam:

    plugin: make

    source: .

    override-build: |
      sudo apt install -y zip
      sudo apt install -y libasound2
      git clone --branch exe https://github.com/xriss/gamecake.git
      gamecake/install
      bash ./make
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp bin/gamecakejam $SNAPCRAFT_PART_INSTALL/bin/gamecakejam
      cp -r cakes $SNAPCRAFT_PART_INSTALL
    
apps:

  gamecakejam:

    command: gamecakejam


slots:
  cakes:
    interface: content
    read: 
      - cakes

